mm:
    encrypt:
        password: Password123
    elasticsearch:
        embedded: true
        address: localhost
        port: 9300
        cluster:
            name: elasticsearch
    plugin:
        defaultStartDate: 08/07/2015

eureka:
    client:
        registerWithEureka: false

spring:
    application:
        name: measurementor