mm:
    encrypt:
        password: Password123
    elasticsearch:
        local: true
        address: localhost
        port: 9300
        cluster:
            name: elasticsearch
    plugin:
        defaultStartDate: 03/07/2015