spring:
    data:
        elasticsearch:
            cluster-node: localhost:9300
            repositories:
                enabled: true
mm:
    proxy:
        set_proxy: false
        url: connsvr.nike.com
        port: 8080
    encrypt:
        password: Password123
    jenkins:
        url: http://192.168.37.90:8080
        path_postfix: /api/json

logging:
    file: mm.log
    level:
        com.nike.mm: DEBUG